FROM pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime


ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get install -y libgomp1

RUN pip install pip --upgrade
RUN pip install pandas click joblib sklearn
RUN pip install numpy==1.13.1
RUN pip install scipy
RUN pip install -U scikit-learn
RUN pip install seaborn
RUN pip install matplotlib
RUN pip install --pre https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.0.0_SNAPSHOT%2Bda6e74f7bb7727ae60b37b1dc6f86ef98d350887-py2.py3-none-manylinux1_x86_64.whl




COPY ./* /code/


RUN chmod +x /code/*
RUN ls -l /code/